// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArRugPPAABphLGkXnbl6RK_eB31oq6ltk',
    appId: '1:849859322485:web:639a45bceecad2afdd4e3c',
    messagingSenderId: '849859322485',
    projectId: 'learntrack-d821e',
    authDomain: 'learntrack-d821e.firebaseapp.com',
    databaseURL: 'https://learntrack-d821e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learntrack-d821e.firebasestorage.app',
    measurementId: 'G-RQJQTVML9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoefud5GXNgCtkYCT0gkNsAMPFhDwm1BE',
    appId: '1:849859322485:android:eb99b31d7998b371dd4e3c',
    messagingSenderId: '849859322485',
    projectId: 'learntrack-d821e',
    databaseURL: 'https://learntrack-d821e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learntrack-d821e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy2Ko_0VyvCaGkM6Awl6KTisduOG-jtxI',
    appId: '1:849859322485:ios:fdf07a15ba6716bfdd4e3c',
    messagingSenderId: '849859322485',
    projectId: 'learntrack-d821e',
    databaseURL: 'https://learntrack-d821e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learntrack-d821e.firebasestorage.app',
    iosBundleId: 'com.example.learnTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy2Ko_0VyvCaGkM6Awl6KTisduOG-jtxI',
    appId: '1:849859322485:ios:fdf07a15ba6716bfdd4e3c',
    messagingSenderId: '849859322485',
    projectId: 'learntrack-d821e',
    databaseURL: 'https://learntrack-d821e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learntrack-d821e.firebasestorage.app',
    iosBundleId: 'com.example.learnTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArRugPPAABphLGkXnbl6RK_eB31oq6ltk',
    appId: '1:849859322485:web:27884bd3927d4247dd4e3c',
    messagingSenderId: '849859322485',
    projectId: 'learntrack-d821e',
    authDomain: 'learntrack-d821e.firebaseapp.com',
    databaseURL: 'https://learntrack-d821e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learntrack-d821e.firebasestorage.app',
    measurementId: 'G-VL2S23WJCD',
  );
}
